In [2]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_carros_cidades.csv")
# pd.read_excel("gerentes_lojas_faturamento.xlsx")

display(df_vendas)

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo do Campo - SP (SBC),Toyota Corolla,18,2340000
1,São Bernardo do Campo - SP (SBC),Volkswagen T-Cross,25,2750000
2,Rio de Janeiro - RJ (RJ),Honda Civic,15,2100000
3,Rio de Janeiro - RJ (RJ),Chevrolet Onix,32,1920000
4,Santa Catarina - SC,Hyundai HB20,28,1960000
5,Santa Catarina - SC,Jeep Compass,12,1800000
6,Teresina - PI (THE),Fiat Toro,20,2600000
7,Teresina - PI (THE),Renault Kwid,35,1400000

In [3]:
#Inspenção
display(df_vendas) #As 5 primeiras linhas e ultimas linhas (No caso todas as linhas)
#display(df_vendas.head(2)) #As 5 primeiras linhas
#display(df_vendas.tail(2)) #As 2 ultimas linhas
# display(df_vendas.sample(3)) #3 linhas aleatorias
# display(df_vendas.shape) #Quantidade de linhas e colunas
# display(df_vendas.columns) #Todas as colunas
# display(df_vendas.info()) #Informações sobre o DataFrame
display(df_vendas.describe()) #Estatisticas descritivas do DataFrame

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo do Campo - SP (SBC),Toyota Corolla,18,2340000
1,São Bernardo do Campo - SP (SBC),Volkswagen T-Cross,25,2750000
2,Rio de Janeiro - RJ (RJ),Honda Civic,15,2100000
3,Rio de Janeiro - RJ (RJ),Chevrolet Onix,32,1920000
4,Santa Catarina - SC,Hyundai HB20,28,1960000
5,Santa Catarina - SC,Jeep Compass,12,1800000
6,Teresina - PI (THE),Fiat Toro,20,2600000
7,Teresina - PI (THE),Renault Kwid,35,1400000

       Quantidade_Vendida  Valor_Total_Vendas
count            8.000000        8.000000e+00
mean            23.125000        2.108750e+06
std              8.219098        4.410195e+05
min             12.000000        1.400000e+06
25%             17.250000        1.890000e+06
50%             22.500000        2.030000e+06
75%             29.000000        2.405000e+06
max             35.000000        2.750000e+06

In [4]:
##Tratamento
df_analise = df_vendas.copy() ##Criando uma copia do DataFrame original


##Colunas
# display(df_analise[["Cidade", "Valor_Total_Vendas"]]) ##Selecionando colunas especificas
df_analise = df_vendas.drop(columns=["Valor_Total_Vendas"]) ##Dropando colunas especificas

##Nulos
# df_analise = df_vendas.fillna(0) ##Substituindo valores nulos por 0
df_analise = df_vendas.dropna() ##Dropando valores nulos

#Tipos de dados
# df_analise["Data"] = pd.to_datetime(df_analise["Data"], format='%Y-%m-%d') #Caso houvesse uma coluna de data esse comando iria formata-lá para o tipo datetime


##Padronização
df_analise["Cidade"] = df_analise["Cidade"].str.title() ##Padronizando para a primeira letra maiuscula
df_analise["Cidade"] = df_analise["Cidade"].str.strip() ##Removendo espaços em branco no inicio e no final da string

##Duplicatas
# df_analise = df_analise.drop_duplicates() ##Dropando duplicatas
# df_analise = df_analise.drop_duplicates(subset=["Cidade"]) ##Dropando duplicatas com base em uma coluna especifica, Se duas cidades forem iguais, apenas a primeira será mantida



display(df_analise)
display(df_analise.info()) #Informações sobre o DataFrame

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000
1,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000
2,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000
3,Rio De Janeiro - Rj (Rj),Chevrolet Onix,32,1920000
4,Santa Catarina - Sc,Hyundai HB20,28,1960000
5,Santa Catarina - Sc,Jeep Compass,12,1800000
6,Teresina - Pi (The),Fiat Toro,20,2600000
7,Teresina - Pi (The),Renault Kwid,35,1400000

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cidade              8 non-null      str
 1   Carro               8 non-null      str
 2   Quantidade_Vendida  8 non-null      int64
 3   Valor_Total_Vendas  8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

None

In [5]:
##Criando colunas

##Faturamento
df_analise["Preço_Unitario"] = df_analise["Valor_Total_Vendas"] / df_analise["Quantidade_Vendida"] ##Criando uma nova coluna com base em outras colunas


##Forma de Venda
df_analise["Forma_de_Venda"] = np.where(df_analise["Quantidade_Vendida"] > 1, "Venda em Lote", "Venda Individual") ##Criando uma nova coluna com base em uma condição

##Região
# display(df_analise["Cidade"].unique()) ##Exibindo valores unicos da coluna Cidade

dic_regioes ={
    'São Bernardo Do Campo - Sp (Sbc)': 'Sudeste',
    'Rio De Janeiro - Rj (Rj)': 'Sudeste',
    'Santa Catarina - Sc': 'Sudeste',
    'Teresina - Pi (The)': 'Nordeste'
}

df_analise["Região"] = df_analise["Cidade"].map(dic_regioes) ##Criando uma nova coluna com base em um dicionario

display(df_analise)
display(df_analise.info()) #Informações sobre o DataFrame
display(df_analise.isna().sum()) #Exibindo a quantidade de valores nulos por coluna

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas,Preço_Unitario,Forma_de_Venda,Região
0,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000,130000.0,Venda em Lote,Sudeste
1,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000,110000.0,Venda em Lote,Sudeste
2,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000,140000.0,Venda em Lote,Sudeste
3,Rio De Janeiro - Rj (Rj),Chevrolet Onix,32,1920000,60000.0,Venda em Lote,Sudeste
4,Santa Catarina - Sc,Hyundai HB20,28,1960000,70000.0,Venda em Lote,Sudeste
5,Santa Catarina - Sc,Jeep Compass,12,1800000,150000.0,Venda em Lote,Sudeste
6,Teresina - Pi (The),Fiat Toro,20,2600000,130000.0,Venda em Lote,Nordeste
7,Teresina - Pi (The),Renault Kwid,35,1400000,40000.0,Venda em Lote,Nordeste

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cidade              8 non-null      str
 1   Carro               8 non-null      str
 2   Quantidade_Vendida  8 non-null      int64
 3   Valor_Total_Vendas  8 non-null      int64
 4   Preço_Unitario      8 non-null      float64
 5   Forma_de_Venda      8 non-null      str
 6   Região              8 non-null      str
dtypes: float64(1), int64(2), str(4)
memory usage: 580.0 bytes

None

Cidade                0
Carro                 0
Quantidade_Vendida    0
Valor_Total_Vendas    0
Preço_Unitario        0
Forma_de_Venda        0
Região                0
dtype: int64

In [7]:
##Analisar -> filtrar

##Ordenando a lista
df_analise = df_analise.sort_values(by="Quantidade_Vendida", ascending=False) ##Ordenando o DataFrame com base em uma coluna especifica
df_analise = df_analise.reset_index(drop=True) ##Resetando o index do DataFrame
##Modos: loc, iloc, condicional

##1: loc || Pesquisando por nome da linha e nome da coluna
cidade = df_analise.loc[2, "Cidade"] ##Selecionando uma linha e coluna especifica
carro = df_analise.loc[2, "Carro"] ##Selecionando uma linha e coluna especifica
preco_unitario = df_analise.loc[2, "Preço_Unitario"] ##Selecionando uma linha e coluna especifica
print(f"A cidade é: {cidade}, o carro é: {carro} e o preço unitario é: {preco_unitario}")

##2: iloc || posição da linha e posição da coluna
cidade = df_analise.iloc[2, 0] ##Selecionando uma linha e coluna especifica
carro = df_analise.iloc[2, 1] ##Selecionando uma linha e coluna especifica
preco_unitario = df_analise.iloc[2, 4] ##Selecionando uma linha e coluna especifica
print(f"A cidade é: {cidade}, o carro é: {carro} e o preço unitario é: {preco_unitario}")

##3: Condicional || Pesquisando por uma condição especifica
df_analise_sbc = df_analise[df_analise["Cidade"] == "São Bernardo Do Campo - Sp (Sbc)"] ##Selecionando todas as linhas onde a coluna Cidade é igual a "São Bernardo Do Campo - Sp (Sbc)"

##Podemos usar o loc com a condicional para selecionar uma linha e coluna especifica
cidade = df_analise.loc[df_analise["Cidade"] == "São Bernardo Do Campo - Sp (Sbc)", "Cidade"].values[0] ##Selecionando uma linha e coluna especifica com base em uma condição e pegando somente os valores da coluna Cidade
carro = df_analise.loc[df_analise["Cidade"] == "São Bernardo Do Campo - Sp (Sbc)", "Carro"].values[0] ##Selecionando uma linha e coluna especifica
preco_unitario = df_analise.loc[df_analise["Cidade"] == "São Bernardo Do Campo - Sp (Sbc)", "Preço_Unitario"].values[0] ##Selecionando uma linha e coluna especifica
print(f"A cidade é: {cidade}, o carro é: {carro} e o preço unitario é: {preco_unitario}")


##4: Duplas condições
condicao1 = df_analise["Valor_Total_Vendas"]>2000000
condicao2 = df_analise["Região"]=="Sudeste"
df_analise_vendas_2mi = df_analise[condicao1 & condicao2]


display(df_analise)
display(df_analise_sbc)
df_analise_sbc.to_csv("Vendas_SBC.csv", index=False) ##Exportando o DataFrame para um arquivo CSV
display(df_analise_vendas_2mi)

A cidade é: Santa Catarina - Sc, o carro é: Hyundai HB20 e o preço unitario é: 70000.0
A cidade é: Santa Catarina - Sc, o carro é: Hyundai HB20 e o preço unitario é: 70000.0
A cidade é: São Bernardo Do Campo - Sp (Sbc), o carro é: Volkswagen T-Cross e o preço unitario é: 110000.0

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas,Preço_Unitario,Forma_de_Venda,Região
0,Teresina - Pi (The),Renault Kwid,35,1400000,40000.0,Venda em Lote,Nordeste
1,Rio De Janeiro - Rj (Rj),Chevrolet Onix,32,1920000,60000.0,Venda em Lote,Sudeste
2,Santa Catarina - Sc,Hyundai HB20,28,1960000,70000.0,Venda em Lote,Sudeste
3,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000,110000.0,Venda em Lote,Sudeste
4,Teresina - Pi (The),Fiat Toro,20,2600000,130000.0,Venda em Lote,Nordeste
5,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000,130000.0,Venda em Lote,Sudeste
6,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000,140000.0,Venda em Lote,Sudeste
7,Santa Catarina - Sc,Jeep Compass,12,1800000,150000.0,Venda em Lote,Sudeste

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas,Preço_Unitario,Forma_de_Venda,Região
3,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000,110000.0,Venda em Lote,Sudeste
5,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000,130000.0,Venda em Lote,Sudeste

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas,Preço_Unitario,Forma_de_Venda,Região
3,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000,110000.0,Venda em Lote,Sudeste
5,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000,130000.0,Venda em Lote,Sudeste
6,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000,140000.0,Venda em Lote,Sudeste

In [23]:
##Analise -> Agrupamento | grupby()
display(df_analise)

#Ranking de faturamento por loja
analise_lojas = df_analise[["Cidade", "Valor_Total_Vendas"]].groupby("Cidade").sum()
analise_lojas = analise_lojas.sort_values("Valor_Total_Vendas", ascending=False)
analise_lojas = analise_lojas.reset_index()
analise_lojas["Valor_Total_Vendas"] = analise_lojas["Valor_Total_Vendas"].map("R${:,.2f}".format)
analise_lojas = analise_lojas.rename(columns={"Valor_Total_Vendas": "Valor Total"})
display(analise_lojas)

analise_qnt_lojas = df_analise[["Cidade", "Quantidade_Vendida"]].groupby("Cidade").sum()
analise_qnt_lojas = analise_qnt_lojas.sort_values("Quantidade_Vendida", ascending=False)
analise_qnt_lojas = analise_qnt_lojas.reset_index()
analise_qnt_lojas = analise_qnt_lojas.rename(columns={"Quantidade_Vendida": "Quantidade de Vendas"})
display(analise_qnt_lojas)

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas,Preço_Unitario,Forma_de_Venda,Região
0,Teresina - Pi (The),Renault Kwid,35,1400000,40000.0,Venda em Lote,Nordeste
1,Rio De Janeiro - Rj (Rj),Chevrolet Onix,32,1920000,60000.0,Venda em Lote,Sudeste
2,Santa Catarina - Sc,Hyundai HB20,28,1960000,70000.0,Venda em Lote,Sudeste
3,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000,110000.0,Venda em Lote,Sudeste
4,Teresina - Pi (The),Fiat Toro,20,2600000,130000.0,Venda em Lote,Nordeste
5,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000,130000.0,Venda em Lote,Sudeste
6,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000,140000.0,Venda em Lote,Sudeste
7,Santa Catarina - Sc,Jeep Compass,12,1800000,150000.0,Venda em Lote,Sudeste

                             Cidade     Valor Total
0  São Bernardo Do Campo - Sp (Sbc)  R$5,090,000.00
1          Rio De Janeiro - Rj (Rj)  R$4,020,000.00
2               Teresina - Pi (The)  R$4,000,000.00
3               Santa Catarina - Sc  R$3,760,000.00

                             Cidade  Quantidade de Vendas
0               Teresina - Pi (The)                    55
1          Rio De Janeiro - Rj (Rj)                    47
2  São Bernardo Do Campo - Sp (Sbc)                    43
3               Santa Catarina - Sc                    40