In [3]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_carros_cidades.csv")
# pd.read_excel("gerentes_lojas_faturamento.xlsx")

display(df_vendas)

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo do Campo - SP (SBC),Toyota Corolla,18,2340000
1,São Bernardo do Campo - SP (SBC),Volkswagen T-Cross,25,2750000
2,Rio de Janeiro - RJ (RJ),Honda Civic,15,2100000
3,Rio de Janeiro - RJ (RJ),Chevrolet Onix,32,1920000
4,Santa Catarina - SC,Hyundai HB20,28,1960000
5,Santa Catarina - SC,Jeep Compass,12,1800000
6,Teresina - PI (THE),Fiat Toro,20,2600000
7,Teresina - PI (THE),Renault Kwid,35,1400000

In [5]:
#Inspenção
display(df_vendas) #As 5 primeiras linhas e ultimas linhas (No caso todas as linhas)
#display(df_vendas.head(2)) #As 5 primeiras linhas
#display(df_vendas.tail(2)) #As 2 ultimas linhas
# display(df_vendas.sample(3)) #3 linhas aleatorias
# display(df_vendas.shape) #Quantidade de linhas e colunas
# display(df_vendas.columns) #Todas as colunas
# display(df_vendas.info()) #Informações sobre o DataFrame
display(df_vendas.describe()) #Estatisticas descritivas do DataFrame

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo do Campo - SP (SBC),Toyota Corolla,18,2340000
1,São Bernardo do Campo - SP (SBC),Volkswagen T-Cross,25,2750000
2,Rio de Janeiro - RJ (RJ),Honda Civic,15,2100000
3,Rio de Janeiro - RJ (RJ),Chevrolet Onix,32,1920000
4,Santa Catarina - SC,Hyundai HB20,28,1960000
5,Santa Catarina - SC,Jeep Compass,12,1800000
6,Teresina - PI (THE),Fiat Toro,20,2600000
7,Teresina - PI (THE),Renault Kwid,35,1400000

       Quantidade_Vendida  Valor_Total_Vendas
count            8.000000        8.000000e+00
mean            23.125000        2.108750e+06
std              8.219098        4.410195e+05
min             12.000000        1.400000e+06
25%             17.250000        1.890000e+06
50%             22.500000        2.030000e+06
75%             29.000000        2.405000e+06
max             35.000000        2.750000e+06

In [ ]:
##Tratamento
df_analise = df_vendas.copy() ##Criando uma copia do DataFrame original


##Colunas
# display(df_analise[["Cidade", "Valor_Total_Vendas"]]) ##Selecionando colunas especificas
df_analise = df_vendas.drop(columns=["Valor_Total_Vendas"]) ##Dropando colunas especificas

##Nulos
# df_analise = df_vendas.fillna(0) ##Substituindo valores nulos por 0
df_analise = df_vendas.dropna() ##Dropando valores nulos

#Tipos de dados
# df_analise["Data"] = pd.to_datetime(df_analise["Data"], format='%Y-%m-%d') #Caso houvesse uma coluna de data esse comando iria formata-lá para o tipo datetime


##Padronização
df_analise["Cidade"] = df_analise["Cidade"].str.title() ##Padronizando para a primeira letra maiuscula
df_analise["Cidade"] = df_analise["Cidade"].str.strip() ##Removendo espaços em branco no inicio e no final da string

##Duplicatas
# df_analise = df_analise.drop_duplicates() ##Dropando duplicatas
# df_analise = df_analise.drop_duplicates(subset=["Cidade"]) ##Dropando duplicatas com base em uma coluna especifica, Se duas cidades forem iguais, apenas a primeira será mantida



display(df_analise)
display(df_analise.info()) #Informações sobre o DataFrame

                             Cidade  Valor_Total_Vendas
0  São Bernardo do Campo - SP (SBC)             2340000
1  São Bernardo do Campo - SP (SBC)             2750000
2          Rio de Janeiro - RJ (RJ)             2100000
3          Rio de Janeiro - RJ (RJ)             1920000
4               Santa Catarina - SC             1960000
5               Santa Catarina - SC             1800000
6               Teresina - PI (THE)             2600000
7               Teresina - PI (THE)             1400000

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000
1,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000
2,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000
3,Rio De Janeiro - Rj (Rj),Chevrolet Onix,32,1920000
4,Santa Catarina - Sc,Hyundai HB20,28,1960000
5,Santa Catarina - Sc,Jeep Compass,12,1800000
6,Teresina - Pi (The),Fiat Toro,20,2600000
7,Teresina - Pi (The),Renault Kwid,35,1400000

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cidade              8 non-null      str
 1   Carro               8 non-null      str
 2   Quantidade_Vendida  8 non-null      int64
 3   Valor_Total_Vendas  8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

None

In [39]:
##Criando colunas

##Faturamento
df_analise["Preço_Unitario"] = df_analise["Valor_Total_Vendas"] / df_analise["Quantidade_Vendida"] ##Criando uma nova coluna com base em outras colunas

display(df_analise)
display(df_analise.info()) #Informações sobre o DataFrame

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas,Preço_Unitario
0,São Bernardo Do Campo - Sp (Sbc),Toyota Corolla,18,2340000,130000.0
1,São Bernardo Do Campo - Sp (Sbc),Volkswagen T-Cross,25,2750000,110000.0
2,Rio De Janeiro - Rj (Rj),Honda Civic,15,2100000,140000.0
3,Rio De Janeiro - Rj (Rj),Chevrolet Onix,32,1920000,60000.0
4,Santa Catarina - Sc,Hyundai HB20,28,1960000,70000.0
5,Santa Catarina - Sc,Jeep Compass,12,1800000,150000.0
6,Teresina - Pi (The),Fiat Toro,20,2600000,130000.0
7,Teresina - Pi (The),Renault Kwid,35,1400000,40000.0

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cidade              8 non-null      str
 1   Carro               8 non-null      str
 2   Quantidade_Vendida  8 non-null      int64
 3   Valor_Total_Vendas  8 non-null      int64
 4   Preço_Unitario      8 non-null      float64
dtypes: float64(1), int64(2), str(2)
memory usage: 452.0 bytes

None