In [15]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_carros_cidades.csv")
# pd.read_excel("gerentes_lojas_faturamento.xlsx")

display(df_vendas)

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo do Campo - SP (SBC),Toyota Corolla,18,2340000
1,São Bernardo do Campo - SP (SBC),Volkswagen T-Cross,25,2750000
2,Rio de Janeiro - RJ (RJ),Honda Civic,15,2100000
3,Rio de Janeiro - RJ (RJ),Chevrolet Onix,32,1920000
4,Santa Catarina - SC,Hyundai HB20,28,1960000
5,Santa Catarina - SC,Jeep Compass,12,1800000
6,Teresina - PI (THE),Fiat Toro,20,2600000
7,Teresina - PI (THE),Renault Kwid,35,1400000

In [23]:
#Inspenção
display(df_vendas) #As 5 primeiras linhas e ultimas linhas (No caso todas as linhas)
#display(df_vendas.head(2)) #As 5 primeiras linhas
#display(df_vendas.tail(2)) #As 2 ultimas linhas
# display(df_vendas.sample(3)) #3 linhas aleatorias
# display(df_vendas.shape) #Quantidade de linhas e colunas
# display(df_vendas.columns) #Todas as colunas
display(df_vendas.info()) #Informações sobre o DataFrame

,Cidade,Carro,Quantidade_Vendida,Valor_Total_Vendas
0,São Bernardo do Campo - SP (SBC),Toyota Corolla,18,2340000
1,São Bernardo do Campo - SP (SBC),Volkswagen T-Cross,25,2750000
2,Rio de Janeiro - RJ (RJ),Honda Civic,15,2100000
3,Rio de Janeiro - RJ (RJ),Chevrolet Onix,32,1920000
4,Santa Catarina - SC,Hyundai HB20,28,1960000
5,Santa Catarina - SC,Jeep Compass,12,1800000
6,Teresina - PI (THE),Fiat Toro,20,2600000
7,Teresina - PI (THE),Renault Kwid,35,1400000

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cidade              8 non-null      str
 1   Carro               8 non-null      str
 2   Quantidade_Vendida  8 non-null      int64
 3   Valor_Total_Vendas  8 non-null      int64
dtypes: int64(2), str(2)
memory usage: 388.0 bytes

None